name: Self-Hosted CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log Node.js version
      run: node --version

    - name: Log available disk space
      run: |
        echo "Checking available disk space:"
        Get-PSDrive -PSProvider FileSystem
      shell: pwsh

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless --no-progress